### ISSUE TITLE
Time is off to the left

### ISSUE THREAD

**Issue by ferike1** [GLolol/lightdm-gtk-greeter-settings-deb#1]
Hello,

I'm using Solus 2017.04.18.0 64-bit with Budgie and using the Adapta theme on the login screen also. I have recently noticed that the time on the login screen is a bit off to the left, see the attachment (I can't take screenshots on the login screen). What could possibly cause this issue? Thank you in advance.

![28636537-b90e027e-723e-11e7-8f37-144bd4b4a07c](https://user-images.githubusercontent.com/29072315/28646475-197e3e62-7262-11e7-8391-706d2dc95b04.jpg)

**Comment by GLolol** [comment]
This looks like https://bugs.launchpad.net/lightdm-gtk-greeter/+bug/1416924
You may be able to fake a centred clock by adding more spacers to the GTK+ greeter panel - the Panel tab in lightdm-gtk-greeter-settings allows you to configure this. Either way, this is a bug in the greeter itself and not the settings program.
